name: Basic Example
on: [push]

jobs:
  armv7_job:
    # The host should always be linux
    runs-on: ubuntu-latest
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v3
      - name: Get the output
        run: |
          echo start
          ls
          docker build --no-cache --tag rk8arm64:latest -f rk8arm64.Dockerfile .
          docker run rk8arm64:latest uname -a
          echo $(docker run rk8arm64:latest uname -a)
          # echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
